CREATE STREAM USUARIO_STREAM (
  AFTER STRUCT< NOME VARCHAR,
  SENHA VARCHAR >
) WITH (
  KAFKA_TOPIC='postgresql.public.user',
  VALUE_FORMAT='JSON'
);

SELECT
  *
FROM
  USUARIO_STREAM_T1 EMIT CHANGES;

CREATE STREAM SINK_USUARIO AS
  SELECT
    NOME_DE_USUARIO AS USER_NAME,
    SENHA           AS USER_PASS
  FROM
    USUARIO_STREAM;