CREATE STREAM IF NOT EXISTS USUARIO (
  AFTER STRUCT < NOME_DE_USUARIO VARCHAR,
  SENHA VARCHAR >
) WITH (
  KAFKA_TOPIC='postgresql.public.usuario',
  VALUE_FORMAT='AVRO'
);

CREATE STREAM IF NOT EXISTS SINK_USUARIO WITH (
  VALUE_FORMAT='AVRO'
) AS
  SELECT
    AFTER -> NOME_DE_USUARIO AS USER_NAME,
    AFTER -> SENHA AS USER_PASS
  FROM
    USUARIO;