mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - 3306:3306